package codegen;

import ast.*;
import semantic.SemanticAnalyzer;

/**
 * Generates valid, executable Python 3 source code directly from a
 * (semantically-checked) কথন AST — the compiler's back-end / target
 * code generation phase.
 *
 * Design notes:
 *   - Bangla variable names (e.g. বয়স) are emitted as-is: Python 3
 *     identifiers may contain any Unicode letter (PEP 3131), so this
 *     requires no name-mangling and stays fully readable.
 *   - সংখ্যা -> Python int, বাক্য -> Python str, boolean conditions ->
 *     Python bool (True/False).
 *   - '+' is polymorphic in কথন (Integer add OR String concat, with
 *     Integer auto-coerced to String — see SemanticAnalyzer). Since
 *     Python's '+' does NOT auto-coerce int+str, this generator reads
 *     each operand's node.resolvedType (filled in by SemanticAnalyzer
 *     during analyze()) and wraps with str(...) whenever the operation
 *     isn't a pure Integer+Integer add.
 *   - '/' is Integer division in কথন (সংখ্যা / সংখ্যা -> সংখ্যা), so it
 *     maps to Python's floor-division operator '//', not '/'.
 *   - This method assumes the program has ALREADY passed semantic
 *     analysis with zero errors — Main.java enforces that before
 *     calling generate().
 */
public class PythonCodeGenerator {

    private final StringBuilder sb = new StringBuilder();
    private static final String INDENT_UNIT = "    "; // 4 spaces, PEP 8

    public String generate(ProgramNode program) {
        sb.setLength(0);
        sb.append("# ============================================================\n");
        sb.append("# Auto-generated by the কথন (Kothon) compiler — Python target code\n");
        sb.append("# Do NOT edit this file directly — edit the .bpl source instead.\n");
        sb.append("# ============================================================\n\n");

        if (program.statements.isEmpty()) {
            sb.append("pass\n");
        } else {
            for (ASTNode stmt : program.statements) {
                genStatement(stmt, 0);
            }
        }
        return sb.toString();
    }

    // ---------------- statements ----------------

    private void indent(int level) {
        for (int i = 0; i < level; i++) sb.append(INDENT_UNIT);
    }

    private void genStatement(ASTNode node, int level) {
        if (node == null) return;

        if (node instanceof DeclarationNode) {
            DeclarationNode d = (DeclarationNode) node;
            indent(level);
            if (d.initializer != null) {
                sb.append(d.varName).append(" = ").append(genCoercedExpr(d.initializer, d.resolvedType)).append("\n");
            } else {
                // Declared but not yet assigned — give it a defined placeholder.
                // (SemanticAnalyzer already guarantees this is never *read*
                // before a real assignment happens later in the program.)
                sb.append(d.varName).append(" = None\n");
            }

        } else if (node instanceof AssignmentNode) {
            AssignmentNode a = (AssignmentNode) node;
            indent(level);
            sb.append(a.varName).append(" = ").append(genCoercedExpr(a.value, a.resolvedType)).append("\n");

        } else if (node instanceof PrintNode) {
            PrintNode p = (PrintNode) node;
            indent(level);
            sb.append("print(").append(genExpr(p.expression)).append(")\n");

        } else if (node instanceof IfNode) {
            IfNode i = (IfNode) node;
            indent(level);
            sb.append("if ").append(genExpr(i.condition)).append(":\n");
            genBlockBody(i.thenBranch, level + 1);
            if (i.elseBranch != null) {
                indent(level);
                sb.append("else:\n");
                genBlockBody(i.elseBranch, level + 1);
            }

        } else if (node instanceof WhileNode) {
            WhileNode w = (WhileNode) node;
            indent(level);
            sb.append("while ").append(genExpr(w.condition)).append(":\n");
            genBlockBody(w.body, level + 1);

        } else if (node instanceof BlockNode) {
            genBlockBody((BlockNode) node, level);
        }
    }

    /** Emits a block's statements indented one level in; emits `pass` if the block is empty (valid Python needs a body). */
    private void genBlockBody(BlockNode block, int level) {
        if (block.statements.isEmpty()) {
            indent(level);
            sb.append("pass\n");
            return;
        }
        for (ASTNode stmt : block.statements) {
            genStatement(stmt, level);
        }
    }

    // ---------------- expressions ----------------

    /**
     * Like genExpr(), but wraps the result in str(...) when the target
     * (declared/assigned-to) type is বাক্য while the expression itself
     * resolved to সংখ্যা — mirroring SemanticAnalyzer's Integer->String
     * coercion rule at the Python level, where no such auto-coercion
     * exists natively.
     */
    private String genCoercedExpr(ASTNode expr, String targetType) {
        String code = genExpr(expr);
        boolean needsCoercion = SemanticAnalyzer.TYPE_STRING.equals(targetType)
                && SemanticAnalyzer.TYPE_INT.equals(expr.resolvedType);
        return needsCoercion ? "str(" + code + ")" : code;
    }

    private String genExpr(ASTNode node) {
        if (node instanceof NumberNode) {
            return String.valueOf(((NumberNode) node).value);
        }
        if (node instanceof StringNode) {
            return pyStringLiteral(((StringNode) node).value);
        }
        if (node instanceof BooleanNode) {
            return ((BooleanNode) node).value ? "True" : "False";
        }
        if (node instanceof VariableNode) {
            return ((VariableNode) node).name;
        }
        if (node instanceof UnaryNode) {
            UnaryNode u = (UnaryNode) node;
            String operand = genExpr(u.operand);
            if (u.operator.equals("না")) return "(not " + operand + ")";
            return "(-" + operand + ")"; // unary '-'
        }
        if (node instanceof BinaryNode) {
            return genBinary((BinaryNode) node);
        }
        return "None";
    }

    private String genBinary(BinaryNode b) {
        String left = genExpr(b.left);
        String right = genExpr(b.right);
        String op = b.operator;

        switch (op) {
            case "এবং": return "(" + left + " and " + right + ")";
            case "অথবা": return "(" + left + " or " + right + ")";
            case "==":  return "(" + left + " == " + right + ")";
            case "!=":  return "(" + left + " != " + right + ")";
            case "<":   return "(" + left + " < " + right + ")";
            case ">":   return "(" + left + " > " + right + ")";
            case "<=":  return "(" + left + " <= " + right + ")";
            case ">=":  return "(" + left + " >= " + right + ")";
            case "-":   return "(" + left + " - " + right + ")";
            case "*":   return "(" + left + " * " + right + ")";
            case "/":   return "(" + left + " // " + right + ")"; // integer division, matches সংখ্যা/সংখ্যা->সংখ্যা
            case "%":   return "(" + left + " % " + right + ")";
            case "+": {
                boolean bothInt = SemanticAnalyzer.TYPE_INT.equals(b.left.resolvedType)
                        && SemanticAnalyzer.TYPE_INT.equals(b.right.resolvedType);
                if (bothInt) return "(" + left + " + " + right + ")";
                // At least one side is String (Integer side auto-coerces) —
                // Python's '+' doesn't do this itself, so wrap both in str().
                return "(str(" + left + ") + str(" + right + "))";
            }
            default:
                return "(" + left + " " + op + " " + right + ")";
        }
    }

    /** Converts a কথন string value into a properly-escaped Python string literal. */
    private String pyStringLiteral(String value) {
        StringBuilder out = new StringBuilder("\"");
        for (char c : value.toCharArray()) {
            if (c == '\\' || c == '"') out.append('\\');
            out.append(c);
        }
        out.append("\"");
        return out.toString();
    }
}
